#!/usr/bin/env bash
# deploy.sh — idempotent deploy of gcal-mcp under PM2.
#
# Runs as the deploy user (NOT root). Other PM2 apps on this server are
# untouched: we only touch the 'gcal-mcp' app via its ecosystem.config.js.
#
# Steps:
#   1. Verify Node.js >= 20 and pm2 are available.
#   2. git pull inside the repo (skipped if not a git worktree).
#   3. npm ci && npm run build.
#   4. Verify .env exists and has required keys; optionally seed .env.secrets
#      with a generated ENCRYPTION_KEY for the operator to copy into .env.
#   5. pm2 startOrReload ecosystem.config.js — starts if new, zero-downtime
#      reload if already running.
#   6. pm2 save. Print pm2 startup instructions only if systemd unit is
#      not yet enabled.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"

APP_NAME="gcal-mcp"
ENV_FILE="$PROJECT_DIR/.env"
ENV_SECRETS_FILE="$PROJECT_DIR/.env.secrets"
REQUIRED_ENV_KEYS=(DATABASE_URL GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET ENCRYPTION_KEY APP_PORT APP_URL)

log()  { printf '\033[1;34m==> [%s]\033[0m %s\n' "$(date +%H:%M:%S)" "$*"; }
warn() { printf '\033[1;33m==> [WARN]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m==> [ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

trap 'die "failed at line $LINENO"' ERR

[[ $EUID -ne 0 ]] || die "do not run as root — use your deploy user"

log "checking Node.js"
command -v node >/dev/null || die "Node.js not found — install Node 20+ (nvm recommended)"
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
(( NODE_MAJOR >= 20 )) || die "Node.js $NODE_MAJOR is too old — need >= 20"

log "checking pm2"
if ! command -v pm2 >/dev/null; then
  log "installing pm2 globally"
  npm install -g pm2
fi

if [[ -d .git ]]; then
  log "git pull"
  git pull --ff-only
else
  warn "not a git worktree — skipping git pull"
fi

log "npm ci"
npm ci

log "npm run build"
npm run build

# --- Secrets handling ---------------------------------------------------------

if [[ ! -f "$ENV_FILE" ]]; then
  # Bootstrap: help operator by generating an encryption key into .env.secrets,
  # but do NOT write a half-populated .env. They must fill Google creds and
  # DATABASE_URL themselves.
  if [[ ! -f "$ENV_SECRETS_FILE" ]]; then
    log "seeding $ENV_SECRETS_FILE with a generated ENCRYPTION_KEY"
    umask 077
    cat > "$ENV_SECRETS_FILE" <<EOF
# Generated by scripts/deploy.sh on $(date -Iseconds)
# Copy ENCRYPTION_KEY into .env, then delete or secure this file.
ENCRYPTION_KEY=$(openssl rand -hex 16)
EOF
    chmod 600 "$ENV_SECRETS_FILE"
  fi
  die ".env is missing. Populate it from .env.example + .env.db + $ENV_SECRETS_FILE, then re-run."
fi

log "verifying required keys in .env"
missing=()
for key in "${REQUIRED_ENV_KEYS[@]}"; do
  if ! grep -qE "^${key}=..*" "$ENV_FILE"; then
    missing+=("$key")
  fi
done
if (( ${#missing[@]} > 0 )); then
  die ".env is missing required keys: ${missing[*]}"
fi

# --- PM2 ----------------------------------------------------------------------

mkdir -p logs

log "pm2 startOrReload ecosystem.config.js"
pm2 startOrReload ecosystem.config.js --update-env

log "pm2 save"
pm2 save

# Only nag about pm2 startup if systemd unit isn't already enabled. This check
# is best-effort — pm2 startup itself is user-specific and requires sudo.
STARTUP_UNIT="pm2-$(whoami)"
if systemctl list-unit-files "$STARTUP_UNIT.service" --no-legend 2>/dev/null | grep -q enabled; then
  log "systemd unit $STARTUP_UNIT is enabled — boot persistence OK"
else
  warn "systemd unit $STARTUP_UNIT is NOT enabled."
  warn "Run once, then execute the command it prints (it will need sudo):"
  warn "    pm2 startup"
fi

log "deploy complete — pm2 status:"
pm2 status "$APP_NAME" || true
