#!/usr/bin/env bash
# setup-db.sh — idempotent PostgreSQL role + database setup for gcal-mcp.
#
# Assumes PostgreSQL is ALREADY installed and running on port 5433 (shared
# with other apps on this server). This script does NOT install, start, or
# reconfigure the postgres service.
#
# Creates role `gcal_mcp` with a generated password and database `gcal_mcp`
# owned by that role. Writes connection details to .env.db (chmod 600) so
# the operator can copy DATABASE_URL into the main .env file.
#
# Re-running is safe: existing role/DB are not recreated. Pass --rotate to
# force-reset the role password and rewrite .env.db.

set -euo pipefail

PG_PORT="${PG_PORT:-5433}"
PG_HOST="${PG_HOST:-localhost}"
DB_NAME="${DB_NAME:-gcal_mcp}"
DB_USER="${DB_USER:-gcal_mcp}"
OWNER=""
ROTATE=0
FORCE=0

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_DB_FILE="$PROJECT_DIR/.env.db"

usage() {
  cat <<EOF
Usage: sudo $0 [--rotate] [--force] [--port PORT] [--db NAME] [--user NAME] [--owner USER]

  --rotate        Reset the role password even if the role already exists.
  --force         Overwrite .env.db if it already exists.
  --port PORT     PostgreSQL port (default: 5433).
  --db NAME       Database name (default: gcal_mcp).
  --user NAME     Role name (default: gcal_mcp).
  --owner USER    chown .env.db to this user. Defaults to \$SUDO_USER if set,
                  otherwise the file is left owned by root (chmod 600).

Must be run as root (uses 'sudo -u postgres psql').
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --rotate) ROTATE=1; shift ;;
    --force)  FORCE=1;  shift ;;
    --port)   PG_PORT="$2"; shift 2 ;;
    --db)     DB_NAME="$2"; shift 2 ;;
    --user)   DB_USER="$2"; shift 2 ;;
    --owner)  OWNER="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

log()  { printf '\033[1;34m==> [%s]\033[0m %s\n' "$(date +%H:%M:%S)" "$*"; }
warn() { printf '\033[1;33m==> [WARN]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m==> [ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

trap 'die "failed at line $LINENO"' ERR

[[ $EUID -eq 0 ]] || die "must run as root (need sudo -u postgres)"

# Resolve ownership for the generated .env.db. Priority:
#   1. --owner flag
#   2. $SUDO_USER (when invoked via sudo from a non-root shell)
#   3. none — file stays owned by root (still chmod 600)
TARGET_USER="$OWNER"
if [[ -z "$TARGET_USER" && -n "${SUDO_USER:-}" && "$SUDO_USER" != "root" ]]; then
  TARGET_USER="$SUDO_USER"
fi

command -v psql >/dev/null || die "psql not found on PATH"

log "checking PostgreSQL reachability on $PG_HOST:$PG_PORT"
sudo -u postgres pg_isready -h "$PG_HOST" -p "$PG_PORT" -q \
  || die "postgres not ready on $PG_HOST:$PG_PORT — verify the cluster is running"

PSQL=(sudo -u postgres psql -h "$PG_HOST" -p "$PG_PORT" -v ON_ERROR_STOP=1)

role_exists() {
  local out
  out=$("${PSQL[@]}" -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'")
  [[ "$out" == "1" ]]
}

db_exists() {
  local out
  out=$("${PSQL[@]}" -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'")
  [[ "$out" == "1" ]]
}

gen_password() {
  # URL-safe password — avoid characters that require escaping in DATABASE_URL.
  openssl rand -base64 36 | tr -d '=+/\n' | cut -c1-32
}

DB_PASSWORD=""

if role_exists; then
  if [[ $ROTATE -eq 1 ]]; then
    log "role '$DB_USER' exists — rotating password (--rotate)"
    DB_PASSWORD="$(gen_password)"
    "${PSQL[@]}" -c "ALTER ROLE \"$DB_USER\" WITH LOGIN PASSWORD '$DB_PASSWORD';" >/dev/null
  else
    warn "role '$DB_USER' already exists — keeping current password (use --rotate to change)"
  fi
else
  log "creating role '$DB_USER'"
  DB_PASSWORD="$(gen_password)"
  "${PSQL[@]}" -c "CREATE ROLE \"$DB_USER\" WITH LOGIN PASSWORD '$DB_PASSWORD';" >/dev/null
fi

if db_exists; then
  log "database '$DB_NAME' already exists — skipping create"
else
  log "creating database '$DB_NAME' owned by '$DB_USER'"
  "${PSQL[@]}" -c "CREATE DATABASE \"$DB_NAME\" OWNER \"$DB_USER\";" >/dev/null
fi

# Only write .env.db when we actually produced a password this run.
if [[ -z "$DB_PASSWORD" ]]; then
  log "no password generated this run — .env.db not modified"
  log "done."
  exit 0
fi

if [[ -f "$ENV_DB_FILE" && $FORCE -ne 1 ]]; then
  warn "$ENV_DB_FILE exists — not overwriting (use --force). Password printed below:"
  printf '\n  DB_PASSWORD=%s\n\n' "$DB_PASSWORD"
  exit 0
fi

log "writing connection details to $ENV_DB_FILE"
umask 077
cat > "$ENV_DB_FILE" <<EOF
# Generated by scripts/setup-db.sh on $(date -Iseconds)
# Copy DATABASE_URL into the main .env file, then delete or secure this file.
DB_HOST=$PG_HOST
DB_PORT=$PG_PORT
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$PG_HOST:$PG_PORT/$DB_NAME
EOF
if [[ -n "$TARGET_USER" ]]; then
  chown "$TARGET_USER":"$TARGET_USER" "$ENV_DB_FILE"
fi
chmod 600 "$ENV_DB_FILE"

log "done. Next: copy DATABASE_URL from $ENV_DB_FILE into $PROJECT_DIR/.env"
